config/routes.rb
Rails.application.routes.draw do
  #RESTful routes
  devise_for :users
  root 'home#index'
  # get '/users/sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
  get 'home/about'
  get 'home/search'
  post '/home/search' => 'home/search'
  get 'currencies/table'

  get 'currencies/new', to: 'currencies#new', as: 'new'
  post 'currencies/new', to: 'currencies#new', as: 'new_currency'

  get 'currencies', to: 'currencies#index', as: 'currencies'
  #post 'currencies', to: 'currencies#index', as: 'currencies_index'

  post 'currencies/sorted', to: 'currencies#sorted', as: 'currencies_sorted'
  get 'currencies/sorted', to: 'currencies#sorted', as: 'currencies_sort'

  post 'currencies/sorted_descending', to: 'currencies#sorted_descending', as: 'currencies_sorted_descending'
  get 'currencies/sorted_descending', to: 'currencies#sorted_descending', as: 'currencies_sorted_desc'

  get 'currencies/:id/edit', to: 'currencies#edit', as: 'edit_currency'
  get 'currencies/:id', to: 'currencies#show', as: 'currency'
  post 'currencies', to: 'currencies#create' 
  
  patch 'currencies/:id', to: 'currencies#update'
  put 'currencies/:id', to: 'currencies#update'
  delete '/currencies/:id', to: 'currencies#destroy'

  post 'portfolios/new', to: 'portfolios#new', as: 'new_portfolio'
  get 'portfolios', to: 'portfolios#index', as: 'portfolios'
  get 'portfolios/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio'

  patch 'portfolios/:id', to: 'portfolios#update'
  put 'portfolios/:id', to: 'portfolios#update'
  delete '/portfolios/:id', to: 'portfolios#destroy'

  post '/portfolios', to: 'portfolios#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
    validates :name, presence: true
    belongs_to :user
	belongs_to :portfolio

    #def portfolio_name
    #    self.try(:portfolio).try(:name)
    #end

    def portfolio_name
        portfolio.name 
    end

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    validates_uniqueness_of :name, scope: :user_id
    validates :name, presence: true
    
    has_many :currencies, :dependent => :destroy
	has_many :users, through: :currencies
end

app/models/user.rb
class User < ApplicationRecord
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
           has_many :currencies
           has_many :portfolios, through: :currencies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController

  def table
    @currencies = Currency.all
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=3faaac7a-4b4d-44d3-9001-1cb1e966e9ce'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @search_coin = JSON.parse(@response)
    @api = 'https://financialmodelingprep.com/api/v3/stock/list?apikey=1d1c39289a199e97b82ab6d6f62bdabb'
    #1d1c39289a199e97b82ab6d6f62bdabb
    @uri2 = URI(@api)
    @response2 = Net::HTTP.get(@uri2)
    @search_stocks = JSON.parse(@response2)
  end

  def index
    if user_signed_in?
      @currencies = Currency.where(user_id: current_user.id)
    else
      redirect_to new_user_session_url, alert: "You must sign in first."
    end
  end

  def sorted
    if user_signed_in?
      @currencies = Currency.where(user_id: current_user.id)
    else
      redirect_to new_user_session_url, alert: "You must sign in first."
    end
  end

  def sorted_descending
    if user_signed_in?
      @currencies = Currency.where(user_id: current_user.id)
    else
      redirect_to new_user_session_url, alert: "You must sign in first."
    end
  end
  
  def show
    @currency = Currency.find(params[:id])
  end

  def new
    @currency = Currency.new
  end

  def create
      @currency = Currency.new(currency_params)
      @currency.user_id = current_user.id
      if @currency.save
        redirect_to @currency
      else
        render :new
      end
  end

  def edit
    @currency = Currency.find(params[:id])
  end

  def update
    @currency = Currency.find(params[:id])
    @currency.update(currency_params)
    if @currency.save
      redirect_to @currency
    else
      render :edit
    end
  end

  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy
    flash[:notice] = "Currency deleted."
    redirect_to currencies_path
  end

  private
  
  def currency_params
    params.require(:currency).permit(:name, :portfolio_id, :portfolio_name, :symbol, :price_per, :amount_owned)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
  
    def about
    end
  
    def search
      require 'net/http'
      require 'json'
      @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=3faaac7a-4b4d-44d3-9001-1cb1e966e9ce'
      @uri = URI(@url)
      @response1 = Net::HTTP.get(@uri)
      @search_coin = JSON.parse(@response1)
      
      @api = 'https://financialmodelingprep.com/api/v3/stock/list?apikey=1d1c39289a199e97b82ab6d6f62bdabb'
      # 1d1c39289a199e97b82ab6d6f62bdabb
      @uri2 = URI(@api)
      @response2 = Net::HTTP.get(@uri2)
      @search_stocks = JSON.parse(@response2)

      @stock = params[:sym]
        if @stock
          @stock = @stock.upcase
      end 
      
      if @stock == "" 
        @stock = "Please enter a stock symbol to search."
      end 

      @symbol = params[:sym] 
        if @symbol
          @symbol = @symbol.upcase
      end
      
      if @symbol == "" 
        @symbol = "Please enter a cryptocurrency symbol to search."
      end
  
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
      if user_signed_in?
          @portfolios = Portfolio.where(user_id: current_user.id)
      else
          redirect_to new_user_session_url, alert: "You must sign in first."
      end
    end
  
    def show
      @portfolio = Portfolio.find(params[:id])
    end
  
    def new
      @portfolio = Portfolio.new
    end
  
    def create
      @portfolio = Portfolio.new(portfolio_params)
      @portfolio.user_id = current_user.id
        if @portfolio.save
          redirect_to @portfolio
        else
          render :new
        end
    end
  
    def edit
      @portfolio = Portfolio.find(params[:id])
    end
  
    def update
      @portfolio = Portfolio.find(params[:id])
      @portfolio.update(portfolio_params)
      if @portfolio.save
        redirect_to @portfolio
      else
        render :edit
      end
    end
  
    def destroy
      @portfolio = Portfolio.find(params[:id])
      @portfolio.destroy
      flash[:notice] = "Portfolio deleted."
      redirect_to portfolios_path
    end
  
    private
  
    def portfolio_params
      params.require(:portfolio).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
    # display portfolios in the currencies index
    def display_portfolio(currency)
        link_to(currency.portfolio_name, portfolio_path(currency.portfolio))
    end
  
    # Display dropdown of portfolio if editing through nested
    def portfolio_select(currency, path)
      if currency.portfolio && path 
        hidden_field_tag "currency[portfolio_id]", currency.portfolio_id
      else
        select_tag "currency[portfolio_id]", options_from_collection_for_select(Portfolio.where(user_id: current_user.id), :id, :name)
      end
    end
  
    # Display name if editing through nested
    def display_name(currency, path)
      if currency.portfolio && path
        currency.portfolio.name
      end
    end
end

app/views/currencies/_form.html.erb
<%= form_for @currency do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% @currency.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <br>
  <%= f.label :portfolio_name %>
  <%= display_name(@currency, @path) %>
  <%= portfolio_select(@currency, @path) %><br>
  
  <div class="field">
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <div class="field">
    <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>
    <div class="field">
    <%= f.label :symbol %>
    <br>
    <%= f.text_field :symbol %>
  </div>
    <br>
  <div class="field">
    <%= f.label :price_per %>
    <br>
    <%= f.text_field :price_per %>
  </div>
    <br>
  <div class="field">
    <%= f.label :amount_owned %>
    <br>
    <%= f.text_field :amount_owned %>
  </div>
    <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing <%= @currency.name %></h1>
<%= render partial: "form" %>

app/views/currencies/index.html.erb
<h2><strong> All Currencies</strong></h2>
<h3><ol>
<% @currencies.each do |currency| %> 
  <li><%= display_portfolio(currency) %> - <%= link_to currency.name, currency_path(currency) %> = <%= (number_to_currency(currency.price_per * currency.amount_owned)) %> |     <%= currency.created_at.in_time_zone("Central Time (US & Canada)").strftime("%B %d, %Y %I:%M %p") %></li><br> 
<% end %> 
</ol></h3>

<h2> <strong> Total Balance: <%= number_to_currency(@currencies.sum { |c| c.price_per * c.amount_owned }) %></strong> </h2>
<br><br>

<%= button_to "Add A New Currency", new_currency_path, class: "btn-group btn-group-justified" %> <br><br>

<%= button_to "Sort by Ascending Order", currencies_sorted_path, class: "btn-group btn-group-justified" %> <br><br>

<%= button_to "Sort by Descending Order", currencies_sorted_descending_path, class: "btn-group btn-group-justified" %> <br><br>

app/views/currencies/new.html.erb
<h1>Create a Currency</h1>
<%= render partial: "form" %>

app/views/currencies/show.html.erb
<h3> Portfolio: <%= display_portfolio(@currency) %></h3>
  <h1> Currency: <%=  @currency.name %></h1>
  <h1> Price per: $ <%= (@currency.price_per) %></h1>
  <h1> Amount Owned: <%= @currency.amount_owned %></h1>
  <h1> Total: <%= number_to_currency(@currency.price_per * @currency.amount_owned) %></h1>

<div>
  <div class="panel-footer"></div>
  <br/>
  <%= link_to 'Edit', edit_currency_path(@currency), class: "btn btn-secondary" %> <br/>
  <%= button_to 'Back to Portfolios', portfolios_path, class: "btn btn-secondary" %> <br/>
  <%= button_to 'Delete', currency_path(@currency), method: :delete, class: "btn btn-danger" %>
</div>

<br>

<%= link_to 'New Currency', new_currency_path, class: "btn btn-primary" %>

app/views/currencies/sorted.html.erb
<h2><strong> All Currencies</strong></h2>
<h3><ol>
<% @currencies.sort_by {|c| c.price_per * c.amount_owned }.each do |currency| %>
  <li><%= display_portfolio(currency) %> - <%= link_to currency.name, currency_path(currency) %> = <%= (number_to_currency(currency.price_per * currency.amount_owned)) %> | <%= currency.created_at.in_time_zone("Central Time (US & Canada)").strftime("%B %d, %Y %I:%M %p") %></li><br> 
<% end %> 
</ol></h3>

<h2> <strong> Total Balance: <%= number_to_currency(@currencies.sum { |c| c.price_per * c.amount_owned }) %></strong> </h2>
<br><br><br><br>


<%= button_to "Add A New Currency", new_currency_path, class: "btn-group btn-group-justified" %> <br><br>

<%= button_to "Sort by Descending Order", currencies_sorted_descending_path, class: "btn-group btn-group-justified" %> <br><br>

app/views/currencies/sorted_descending.html.erb
<h2><strong> All Currencies</strong></h2>
<h3><ol>
<% @currencies.sort_by {|c| -c.price_per * c.amount_owned }.each do |currency| %>
  <li><%= display_portfolio(currency) %> - <%= link_to currency.name, currency_path(currency) %> = <%= (number_to_currency(currency.price_per * currency.amount_owned)) %> | <%= currency.created_at.in_time_zone("Central Time (US & Canada)").strftime("%B %d, %Y %I:%M %p") %></li><br> 
<% end %> 
</ol></h3>

<h2> <strong> Total Balance: <%= number_to_currency(@currencies.sum { |c| c.price_per * c.amount_owned }) %></strong> </h2>
<br><br><br><br>


<%= button_to "Add A New Currency", new_currency_path, class: "btn-group btn-group-justified" %> <br><br>

<%= button_to "Sort by Ascending Order", currencies_sorted_path, class: "btn-group btn-group-justified" %> <br><br>

app/views/currencies/table.html.erb
<h1>Cryptocurrencies Portfolio</h1>
<br/>
<table class="table table-hover table-bordered table-striped">
    <thead class='thead-dark'>
      <tr>
        <th>Name</th>
        <th>Symbol</th>
        <th>Rank</th>
        <th>1 HR</th>
        <th>24 HR</th>
        <th>7D</th>
        <th>Current Price</th>
        <th>Total Value</th>
        <th>Total Paid</th>
        <th>Profits/Losses
        <th>Cost per Coin</th>
        <th>Coins owned</th>
      </tr>
    </thead>
    <% profit_loss = 0 %>
    
    <tbody>
        <% @currencies.each do |currency| %>
            <% if currency.user_id == current_user.id %>
            <tr>
            <% for x in @search_coin['data'] %>
                <% if currency.symbol == x['symbol'] %>
                    <td><%= link_to x['name'], currency %></td>
                    <td><%= currency.symbol %></td>
                    <td><%= x["cmc_rank"]%></td>
                    <td><%= x['quote']['USD']['percent_change_1h'].round(2) %>%</td>
                    <td><%= x['quote']['USD']['percent_change_24h'].round(2)  %>%</td>
                    <td><%= x['quote']['USD']['percent_change_7d'].round(2)  %>%</td>
                    <td>$<%= x['quote']['USD']['price'].round(5) %></td>
                    <td>$<%= (x['quote']['USD']['price'].to_d * currency.amount_owned).round(2) %></td>
                    <td>$<%= (currency.price_per * currency.amount_owned).round(2) %>
                    <td>$<%= ((x['quote']['USD']['price'].to_d * currency.amount_owned) - (currency.price_per * currency.amount_owned)).round(2) %></td>
                    <td>$<%= currency.price_per %></td>
                    <% profit_loss += ((x['quote']['USD']['price'].to_d * currency.amount_owned) - (currency.price_per * currency.amount_owned)).round(2) %>
                    <td><%= (currency.amount_owned).round(2) %></td>
                <% end %>
            <% end %>
            </tr>
            <% end %>
        <% end %>
    </tbody>
</table>
<br>
<br>
<strong>Total Portfolio Profits/Losses:</strong> <%= number_to_currency(profit_loss) %>
<br>
<br>
<h1>Stocks Portfolio</h1>
<br/>
<table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Symbol</th>
        <th>Current Cost per Share</th>
        <th>Amount Paid</th>
        <th>Shares owned</th>
        <th>Price When Bought</th>
        <th>Profits/Losses</th>
      </tr>
    </thead>
    <% profit_losses = 0 %>
    
    <tbody>
        <% @currencies.each do |currency| %>
            <% if currency.user_id == current_user.id %>
            <tr>
            <% for x in @search_stocks %>
                <% if currency.symbol == x['symbol'] && x['name'].include?(currency.name) %>
                    <td><%= link_to x['name'], currency %></td>
                    <td><%= x['symbol'] %></td>
                    <td><%= number_to_currency(x['price']) %></td>
                    <td><%= number_to_currency(currency.price_per * currency.amount_owned) %></td>
                    <td><%= currency.amount_owned %></td>
                    <td><%= number_to_currency(currency.price_per) %></td>
                    <td><%= number_to_currency((x['price'] * currency.amount_owned) - (currency.price_per * currency.amount_owned)) %></td>
                    <% profit_losses += (x['price'] * currency.amount_owned) - (currency.price_per * currency.amount_owned) %>
                <% end %> 
            <% end %>
            </tr>
            <% end %>
        <% end %>
    </tbody>
</table>
<br>
<br>
<strong>Total Portfolio Profits/Losses:</strong> <%= number_to_currency(profit_losses) %>
<br>
<br>
<%= button_to 'Add A New Currency', new_currency_path, class: "btn btn-default" %>
<br>
<br>
<br>
<br>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %> 
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Investing Portfolios", portfolios_path, class: "navbar-brand" %>
      <%= link_to "All Currencies", currencies_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

     
      <ul class="nav navbar-nav navbar-right">

      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About Us", home_about_path %></li>
      <li><%= link_to "Search", home_search_path %></li>
      

      <% if user_signed_in? %>
        <li><%= link_to "Cryptos and Stocks Table", currencies_table_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Us</h2>
<p>Here at Finance Portfolios we want to help people manage their finances as easily as possible while having fun doing it. Managing one's portfolios has never been more easier! </p>



<%= image_tag "investing 9.jpg", height: 225 %>
<%= image_tag "investing 5.jpg", height: 225 %>
<%= image_tag "investing 6.jpg", height: 225 %>

app/views/home/index.html.erb
<h1>Welcome to your Finance Portfolios App!</h1>
<h3>Think Tech. Think Investing. Learn to diversify your portfolios.
We make 0 Commissions and no deposit minimums.
Everyone gets better tools for better investing.</h3>

<br><br>
<h1><%= link_to "Sign Up Today", new_user_registration_path %></h1>
<br><br>

<br>

<%= image_tag "shibainu1.jpg", height: 225 %>
<%= image_tag "investing 2.jpg", height: 225 %>
<%= image_tag "investing 3.jpg", height: 225 %>

app/views/home/search.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Search for a specific cryptocurrency or stock.</h3>
  </div>
<div class="panel-body">

<br>

<%= form_tag home_search_path, :method => 'POST' do %>
    <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto or Stock Symbol', size: 50 %>
    <%= submit_tag 'Lookup Quote' %>
<% end %>

<br><br>

<% if @symbol %>
    <% for x in @search_coin['data'] %>
        <% if @symbol == x['symbol'] %>
           <strong><%= x['name'] %></strong> <br><br>
           <strong><%= x['symbol'] %></strong> <br><br>
           <strong>$ <%= x['quote']['USD']['price'] %></strong> <br><br>
           <strong> Rank: <%= x['cmc_rank'] %></strong> <br><br>
        <% end %>
    <% end %>
    
<% end %>
<% if @stock %>
    <% for x in @search_stocks %>
        <% if @stock == x['symbol'] %>
           <strong><%= x['symbol'] %></strong> <br><br>
           <strong><%= x['name'] %></strong> <br><br>
           <strong>$ <%= x['price'] %></strong> <br><br>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Investing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', "data-turbo-track": "reload" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body>
  <%= render "home/navbar" %>

  <div class="container" >
    <%= render "home/flash" %>
    <%= yield %>
  </div>
  <br><br><br><br><br><br><br><br><br><br><br><br>
  <footer class="branding">
        <small>&copy; Copyright <strong> Daniel Muchiri 2022 </strong></small>  
  </footer>
  </body>
</html>

app/views/portfolios/edit.html.erb
<h1>Editing <%= @portfolio.name %></h1>

<%= form_for @portfolio  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/portfolios/index.html.erb
<h2><strong> Portfolios</strong></h2>

  <h3> <ol>
  <% @portfolios.each do |portfolio| %>
    <li> <%= link_to portfolio.name, portfolio_path(portfolio) %></li>
  <br>
  <% end %>
  </ol></h3>

<%= button_to "Add A New Portfolio", new_portfolio_path, class: "btn-group btn-group-justified" %>

app/views/portfolios/new.html.erb
<h1>Create a Portfolio</h1>

<%= form_for @portfolio do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% @portfolio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label> Portfolio </label>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  
  <div class="field">
    <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <%= f.submit %>
<% end %>

app/views/portfolios/show.html.erb
<h1><%= @portfolio.name %></h1>
<ul>
  <% @portfolio.currencies.each do |currency| %>
    <li><%= link_to currency.name, currency_path(currency) %></li>
  <% end %>
</ul>

<div>
  <div class="panel-footer"></div>
  <br/>
  <%= button_to 'Edit', edit_portfolio_path(@portfolio), class: "btn btn-secondary" %> <br/>
  <%= button_to 'Back to Portfolios', portfolios_path, class: "btn btn-secondary" %> <br/>
  <%= button_to 'Delete', portfolio_path(@portfolio), method: :delete, class: "btn btn-danger" %>
</div>